# parking-management/backend/scripts/maintenance/config/maintenance.config.sh
# Maintenance configuration

# General Settings
MAINTENANCE_LOCK_FILE="/tmp/${APP_NAME:-parking-management}.maintenance.lock"
MAINTENANCE_WINDOW_START="${MAINTENANCE_WINDOW_START:-02:00}" # 2 AM
MAINTENANCE_WINDOW_END="${MAINTENANCE_WINDOW_END:-04:00}" # 4 AM
MAX_SYSTEM_LOAD="${MAX_SYSTEM_LOAD:-2.0}" # Don't run if load > 2.0
MAINTENANCE_LOG_DIR="${MAINTENANCE_LOG_DIR:-./maintenance_logs}"

# Database Maintenance
VACUUM_THRESHOLD="${VACUUM_THRESHOLD:-20}" # Percentage of dead tuples
ANALYZE_THRESHOLD="${ANALYZE_THRESHOLD:-10}" # Percentage of modified rows
REINDEX_THRESHOLD_DAYS="${REINDEX_THRESHOLD_DAYS:-30}" # Days since last reindex
INDEX_BLOAT_THRESHOLD="${INDEX_BLOAT_THRESHOLD:-50}" # Percentage bloat
TABLE_BLOAT_THRESHOLD="${TABLE_BLOAT_THRESHOLD:-30}" # Percentage bloat

# Log Maintenance
LOG_RETENTION_DAYS="${LOG_RETENTION_DAYS:-30}"
LOG_MAX_SIZE_MB="${LOG_MAX_SIZE_MB:-100}"
LOG_COMPRESSION_ENABLED="${LOG_COMPRESSION_ENABLED:-true}"
LOG_ROTATION_COUNT="${LOG_ROTATION_COUNT:-10}"

# Cache Maintenance
REDIS_MAX_MEMORY_MB="${REDIS_MAX_MEMORY_MB:-1024}" # 1GB
REDIS_EVICTION_POLICY="${REDIS_EVICTION_POLICY:-allkeys-lru}"
CACHE_CLEAR_BEFORE_PERCENT="${CACHE_CLEAR_BEFORE_PERCENT:-80}" # Clear if >80% full

# Backup Maintenance
BACKUP_RETENTION_DAYS="${BACKUP_RETENTION_DAYS:-30}"
BACKUP_VERIFICATION_ENABLED="${BACKUP_VERIFICATION_ENABLED:-true}"
BACKUP_MIN_FREE_SPACE_GB="${BACKUP_MIN_FREE_SPACE_GB:-10}" # Minimum free space in GB

# Cleanup Settings
TEMP_FILE_AGE_HOURS="${TEMP_FILE_AGE_HOURS:-24}"
ORPHANED_UPLOADS_AGE_DAYS="${ORPHANED_UPLOADS_AGE_DAYS:-7}"
SESSION_CLEANUP_AGE_HOURS="${SESSION_CLEANUP_AGE_HOURS:-24}"
FAILED_JOBS_CLEANUP_DAYS="${FAILED_JOBS_CLEANUP_DAYS:-7}"

# Monitoring
HEALTH_CHECK_TIMEOUT="${HEALTH_CHECK_TIMEOUT:-30}"
ALERT_THRESHOLD_ERROR_RATE="${ALERT_THRESHOLD_ERROR_RATE:-5}" # Percentage
ALERT_THRESHOLD_RESPONSE_TIME="${ALERT_THRESHOLD_RESPONSE_TIME:-1000}" # ms

# Create log directory
mkdir -p "${MAINTENANCE_LOG_DIR}"

# Export variables
export MAINTENANCE_LOCK_FILE MAINTENANCE_WINDOW_START MAINTENANCE_WINDOW_END
export MAX_SYSTEM_LOAD VACUUM_THRESHOLD ANALYZE_THRESHOLD LOG_RETENTION_DAYS
export BACKUP_RETENTION_DAYS TEMP_FILE_AGE_HOURS