# Yarn 2+ configuration

nodeLinker: node-modules

npmRegistryServer: "https://registry.npmjs.org/"

enableGlobalCache: true

enableTelemetry: false

enableScripts: true

enableImmutableInstalls: true

enableProgressBars: true

logFilters:
  - code: YN0002
    level: discard
  - code: YN0060
    level: discard
  - code: YN0013
    level: discard

packageExtensions:
  "@mui/material@*":
    dependencies:
      "@emotion/react": "*"
      "@emotion/styled": "*"
  "react-dom@*":
    dependencies:
      "react": "*"

yarnPath: .yarn/releases/yarn-4.0.2.cjs