apiVersion: v1
kind: Secret
metadata:
  name: postgres-secret
  namespace: parking-system
type: Opaque
stringData:
  POSTGRES_PASSWORD: "P@rkingDB2024!Secure"
  POSTGRES_REPLICATION_PASSWORD: "ReplP@ss2024!"
  POSTGRES_READONLY_PASSWORD: "ReadOnly2024!"
---
apiVersion: v1
kind: Secret
metadata:
  name: kong-postgres-secret
  namespace: parking-system
type: Opaque
stringData:
  KONG_PG_PASSWORD: "KongDB2024!Secure"